### PR TITLE
Ensure that log path is endend with / and log file has a ".log" extension

### PR DESCRIPTION
**Pull request by kl3sk**

### CODE REVIEW

**Comment by Chris53897** [comment]
@kl3sk 
As this could lead to problems at userland code, this is change is ok for master. As master will be relesed as a major version.

Please add a Help-Text for the form field. And a Assert in the entity to force validation. Otherwise problems will only be visible at runtime if user are using other file-endings. 
And plesae add a entry in the Readme-File for Version 6 (needs new section).

**Comment by Chris53897** [comment]
Can you please fix the failing tests? I guess other extension than '.log' in tests?

**Comment by Chris53897** [comment]
What are other users thinking of forcing the file-extension?
I am not 100% convinced that this should be forced.

**Comment by Chris53897** [comment]
I was wrong with my guess. All tests have a '.log' suffix
https://github.com/Dukecity/CommandSchedulerBundle/blob/master/Fixtures/ORM/LoadScheduledCommandData.php#L29

Looks like this regex is not correct.
https://github.com/Dukecity/CommandSchedulerBundle/pull/73/files#diff-756a353f2da317e23470760e4811af1f550c060546f9c94046db6f3f44add28bR65

[critical] Uncaught PHP Exception ErrorException: "Warning: preg_match(): No ending delimiter '/' found" at /home/runner/work/CommandSchedulerBundle/CommandSchedulerBundle/vendor/symfony/validator/Constraints/RegexValidator.php line 50

**Comment by kl3sk** [comment]
Sounds good now.

**Comment by kl3sk** [comment]
@Chris53897 did you have any clues ?

**Comment by kl3sk** [comment]
ping @Chris53897 

Is this enough to merge ?
Thanks

**Comment by Chris53897** [comment]
Thanks @kl3sk 

Small info:
I was not sure about the merge from master into your branch.
A better way would have been to use `git rebase master your/branch`

This will be part of version 6.
Release will be after all dependencies will support syymfony 7.
I am already working on this.

**Comment by kl3sk** [comment]
Hello,

I'am not sure to understand. 

You want to have this PR in V6 but working on the same for V7 ?

Anyway I'll rebase as you requested. 

Thanks.

**Comment by Chris53897** [comment]
I just updated README.md for the version infos.
I merged this PR for new major version (6) of this bundle. Which will bump dependencies and supports Symfony 7.
https://github.com/Dukecity/CommandSchedulerBundle?tab=readme-ov-file#versions--dependencies

This is a BC break, that i can not add in 5.x.

Does this info helps?

**Comment by Chris53897** [comment]
>> A rebase is still required ?
No. Everthink is fine. thanks again

**Comment by kl3sk** [comment]
Great news. Thanks for your work.

**Pull request merged**
