### PR TITLE
WIP: fix: correct behavior for commands that were never executed

### PR DESCRIPTION
**Pull request by petski**
See #63

### CODE REVIEW

**Comment by petski** [comment]
Feedback more than desired.

**Comment by Chris53897** [comment]
thanks @petski 
I have tested it and looks good.
An additonally UnitTest would be great. But i will merge in the actual state

**Comment by petski** [comment]
😅 I marked this PR as "WIP" because I was still working on it. Had some extra thoughts about my approach and I think it's not fail safe, as it doesn't take this scenario into account:

- job x without last execution with `0 * * * *`
- scheduler doing a 5 minute job y at 11:59
- scheduler re-runs at 12:04
- job x isn't due, so not started

I think in hindsight it's best to take the creation time of the job as a reference (were the last execution time is that for jobs that already ran at least once).

My advice would be to revert this PR for the time being.

Feedback more than welcome

**Comment by Chris53897** [comment]
Ok, sorry. I reverted the last commit.

In that case more UnitTests are necessary to cover this cases.
Can you create this tests are we will see if your changes cover these cases?
This will help this repo in general.

I am not sure i can help more at this time.

**Pull request merged**
